# "Hello World"

#    E D A = Explotary Data Analytics 
   

In [ ]:
# *****              ANACONDA 3
                 1 :> Numpy 
        
                 2:> Pandas
                
                 3:> Matplotlib Visualization
                        
                 4 :> SeaBorn
                    
                 5 :> SciKit Learn
                    
                   [ Jupiter NoteBook.> Save Any File in (ipnby)]
                    [ Kernel ->  Execute Code ]
                    

# ******************* DATA TYPE >> **************

1  :> int -> 10,20,30,40,50,60,70, etc
    
2  :> flot -> 3.14,2.32,4.25,8.2,5.14,etc
    
3  :> boolean -> True, False 
    
4  :> String -> "Sam","Mat","Bob","John",etc
    
5  :> Complex -> 3+4i, 3-2i,5+8i,etc    
    
            @@@@@@@@@@@ OPERATORS IN PYTHON  @@@@@@@@@@@@
        
        1 :> Arithmatic Operators ->> (+,-,*,/)
          
        2  :> Relational Operators->>> (<,>,==,!=)
            
        3  :> Logical Operators ->>>>(&,|)
            
            $$$$$$$$$$$$$  PYTHON TOKEN  $$$$$$$$$$$$$$$
            
 1  :> KEYWORDS -> Special reserved words->>> False, True , finally, is , return , None, continue, for, lambda,  class, def,
                                             from, nonlocal, while, and, del, global, not, with, as, elif, if, or, yield, etc
    
 2  :> IDENTIFIERS -> Identifiers are used for variables, functions or objects.
    
    Rule :> 1-> No Special charector expect (underscore).
        
            2 -> Identifiers are case sensitive. 
            
            3 -> First letter Can't be a digit.
            
 3 :> LITERALS ->  Literals are constants in python .
        
        "Hello World" = Literal
        
            Strings are sequence of charactor enclosed within Single quotes (''), Double quotes(""), or Triple quotes ("'a')
                                                                                                                       .  

In [203]:
"Hello World"

'Hello World'

In [23]:
"This is Sparta"

'This is Sparta'

In [24]:
'"I am going to France"'

'"I am going to France"'

# Extract individual charecters

In [2]:
my_string= "My name is Bharat Bhooshan"
my_string

'My name is Bharat Bhooshan'

In [3]:
my_string[0]

'M'

my_string[4]

# 1- Finding String Lengths

In [32]:
len(my_string)

26

# 2- Converting into Lower Case

In [33]:
my_string.lower()

'my name is bharat bhooshan'

# 3- Converting Upper Case

In [34]:
my_string.upper()

'MY NAME IS BHARAT BHOOSHAN'

# 4-Replacing a Substring

In [36]:
my_string.replace('name','nam')

'My nam is Bharat Bhooshan'

# 5- Number of occurance of Substring

In [40]:
 new_string="Hello Hello World"

In [41]:
new_string.count("Hello")

2

# 6- Finding the index of Substring

In [42]:
s1="This is Sparta"

In [43]:
s1.find('Sparta')

8

# 7- Spliting A String

In [44]:
fruit="I Like Apples,Mangoes, Bananas"

In [49]:
fruit.find(',')

13

In [53]:
fruit.split(',')

['I Like Apples', 'Mangoes', ' Bananas']

# Data structure in Python
1- TUPLE,
2- LIST,
3- DICTIONARY,
4- SET

In [59]:
tup1=(1,"a",True,2,"b",False)

# Extracting individual elements 

In [63]:
tup1[2]

True

In [64]:
tup1[-1]

False

In [65]:
tup1[1:4]

('a', True, 2)

In [ ]:
for finding tuple length > len(tup1) + Shift + Enter 
for maximum > max(tup1) + Shift + Enter
for minimum > min(tup1) + Shift + Enter

# LIST IN PYTHON :-> List in an orderd collection of elements enclosed with []
    * Lists are Mutable[1,"a",True]
    LIST is denoted by l
EXTRACTING INDIVIDUAL ELEMENTS >>>>>>>>>>>>>>.

In [67]:
l1=[1,"a",2,"b",3,"c",4,"d",5,"e",6,"f"]

In [68]:
l1[2]

2

In [69]:
l1[5]

'c'

In [70]:
l1[2:6]

[2, 'b', 3, 'c']

In [71]:
l1[1:8]

['a', 2, 'b', 3, 'c', 4, 'd']

# 1 :> Modified a Lists :-> Changing the element At 0^th index 

In [72]:
l1=[1,"a",2,"b",3,"c",4,"d",5,"e",6,"f"]

In [73]:
l1[0]=100

In [74]:
l1

[100, 'a', 2, 'b', 3, 'c', 4, 'd', 5, 'e', 6, 'f']

In [75]:
l1[5]=25

In [76]:
l1

[100, 'a', 2, 'b', 3, 25, 4, 'd', 5, 'e', 6, 'f']

In [77]:
l1[8]=68

In [78]:
l1

[100, 'a', 2, 'b', 3, 25, 4, 'd', 68, 'e', 6, 'f']

# 2 :> Popping the Last Element>>>>>>>>>>>

In [85]:
l1=[1,"a",2,"b",3,"c",4,"d",5,"e",6,"f"]

In [86]:
l1.pop()

'f'

In [87]:
l1.pop()

6

In [89]:
l1.pop()

'e'

In [90]:
l1.pop(-5)

3

In [91]:
l1.pop(6)

'd'

# 3 :> Appending a New Element>>>>>>>>>>

In [92]:
l1=[1,"a",2,"b",3,"c",4,"d",5,"e",6,"f"]

In [93]:
l1.append("SPARTA")

In [94]:
l1

[1, 'a', 2, 'b', 3, 'c', 4, 'd', 5, 'e', 6, 'f', 'SPARTA']

In [95]:
l1.append ("John")
l1

[1, 'a', 2, 'b', 3, 'c', 4, 'd', 5, 'e', 6, 'f', 'SPARTA', 'John']

In [96]:
l1.append("Mick")
l1

[1, 'a', 2, 'b', 3, 'c', 4, 'd', 5, 'e', 6, 'f', 'SPARTA', 'John', 'Mick']

# 4 :> Reverse Elements of a List:>>>>>>>>>>>>..

In [97]:
l1=[1,"a",2,"b",3,"c",4,"d",5,"e",6,"f"]

In [98]:
l1.reverse()

In [99]:
l1

['f', 6, 'e', 5, 'd', 4, 'c', 3, 'b', 2, 'a', 1]

In [102]:
l1.reverse()

In [103]:
l1

[1, 'a', 2, 'b', 3, 'c', 4, 'd', 5, 'e', 6, 'f']

# 5 :> Inserting element at a Specified index >>>>>>>>>>>>

In [104]:
l1=[1,"a",2,"b",3,"c",4,"d",5,"e",6,"f"]

In [105]:
l1.insert(1,"Sparta")

In [106]:
l1

[1, 'Sparta', 'a', 2, 'b', 3, 'c', 4, 'd', 5, 'e', 6, 'f']

# 6 :> Sorting a List :>>>>>>>>>>>>>

In [116]:
l1=["Mangoes","Apples","Bananas","Guava"]
l1

['Mangoes', 'Apples', 'Bananas', 'Guava']

In [118]:
l1.sort()
l1

['Apples', 'Bananas', 'Guava', 'Mangoes']

# 7 :> Concatenating a Lists :>.............

In [127]:
l1=[1,2,3,4]

In [128]:
l2=["a","b","c","d"]

In [129]:
l1 + l2

[1, 2, 3, 4, 'a', 'b', 'c', 'd']

# 8 :> Repeating Elements >>>>>>>>>>>>.

In [131]:
l1=[1,"a",True]

In [132]:
l1*3

[1, 'a', True, 1, 'a', True, 1, 'a', True]

In [136]:
l1=[1,"a",True,2,"b",False]

In [137]:
l2=[3,"c",True,4,"d",False]

In [138]:
l1*2 +l2*2

[1,
 'a',
 True,
 2,
 'b',
 False,
 1,
 'a',
 True,
 2,
 'b',
 False,
 3,
 'c',
 True,
 4,
 'd',
 False,
 3,
 'c',
 True,
 4,
 'd',
 False]

In [140]:
l1*2

[1, 'a', True, 2, 'b', False, 1, 'a', True, 2, 'b', False]

In [141]:
l2*2

[3, 'c', True, 4, 'd', False, 3, 'c', True, 4, 'd', False]

# **** Dictionary In Python :> Dictionary is an Unordered collection of Key-Value pairs Enclosed with{}
** Dictionary is Mutable 
Fruit = {"Apple",:10,"Orange",:20}
"Apple"= Key
10= Value
***Extracting Key & Value 

In [177]:
fruit={"Apple":10,"Orange":20}
fruit

{'Apple': 10, 'Orange': 20}

In [178]:
fruit.keys()

dict_keys(['Apple', 'Orange'])

In [179]:
fruit.values()

dict_values([10, 20])

# 1 :> Adding a New element:>..

In [180]:
fruit={"Apple":10,"Orange":20,"Banana":30,"Mango":40}

In [184]:
fruit["Guava"]=50
fruit

{'Apple': 10, 'Orange': 20, 'Banana': 30, 'Mango': 40, 'Guava': 50}

In [185]:
fruit["Pineapple"]=65
fruit

{'Apple': 10,
 'Orange': 20,
 'Banana': 30,
 'Mango': 40,
 'Guava': 50,
 'Pineapple': 65}

# 2 :> Changing the Existing elements>>>>>>>>>>>>>>>>

In [186]:
fruit={"Apple":10,"Orange":20,"Banana":30,"Mango":40}

In [188]:
fruit["Apple"]=52
fruit

{'Apple': 52, 'Orange': 20, 'Banana': 30, 'Mango': 40}

In [190]:
fruit["Mango"]=69
fruit

{'Apple': 52, 'Orange': 20, 'Banana': 30, 'Mango': 69}

# 3 :> Update one Dictinary's Elements with Another

In [191]:
fruit1={"Apple":10,"Orange":20,"Banana":30,"Mango":40}

In [192]:
fruit2={"Guava":50,"Pineapple":60,"Carrot":70,"Lemon":80}

In [194]:
fruit1.update(fruit2)
fruit1

{'Apple': 10,
 'Orange': 20,
 'Banana': 30,
 'Mango': 40,
 'Guava': 50,
 'Pineapple': 60,
 'Carrot': 70,
 'Lemon': 80}

In [195]:
fruit1={"Apple":10,"Orange":20}
fruit2={"Guava":50,"Pineapple":60}

In [196]:
fruit1

{'Apple': 10, 'Orange': 20}

In [197]:
fruit2

{'Guava': 50, 'Pineapple': 60}

In [198]:
fruit1.update(fruit2)
fruit1

{'Apple': 10, 'Orange': 20, 'Guava': 50, 'Pineapple': 60}

In [199]:
fruit2.update(fruit1)
fruit2

{'Guava': 50, 'Pineapple': 60, 'Apple': 10, 'Orange': 20}

# 3 :> Popping an Element:>>>>>>>>>>>>

In [6]:
fruit2={"Guava":50,"Pineapple":60,"Carrot":70,"Lemon":80}
fruit2

{'Guava': 50, 'Pineapple': 60, 'Carrot': 70, 'Lemon': 80}

In [7]:
fruit2.pop("Lemon")
fruit2

{'Guava': 50, 'Pineapple': 60, 'Carrot': 70}

In [9]:
fruit2.pop("Carrot")
fruit2

{'Guava': 50, 'Pineapple': 60}

# ***** Set in Python :> Set is an ordered and unindexed collection of elements enclosed with curly brases {}.
        
        * Duplicates are not allowed in set and unextracting in set .
        
        s1={1,"a",True}

In [205]:
s1={1,"a",True}
s1

{1, 'a'}

# 1 -> Update one Dictionary's elements with Another  ->

In [206]:
s1={1,"a",True,2,"b",False}

In [207]:
s1.add("Hello")
s1

{1, 2, False, 'Hello', 'a', 'b'}

# 2 :> Updating Multiple Elements ->>>>>

In [209]:
s1={1,"a",True,2,"b",False}

In [213]:
s1.update([10,20,30])
s1

{1, 10, 2, 20, 30, False, 'a', 'b'}

# 3 :> Removing An Elements ->>>>>>

In [214]:
s1={1,"a",True,2,"b",False}

In [215]:
s1.remove("b")
s1

{1, 2, False, 'a'}

#     @@@@@@@@@@@  SET FUNCTIONS  @@@@@@@@@@


# 1 :> Union of 2 Sets ->>>>>>>>>>>>

In [217]:
s1={1,2,3}

In [218]:
s2={"a","b","c"}

In [219]:
s1.union (s2)

{1, 2, 3, 'a', 'b', 'c'}

# 2 :> Intersection of 2- Sets ->>>>>>>..

In [220]:
s1={1,2,3,4,5,6,}

In [221]:
s2={5,6,7,8,9}

In [223]:
s1.intersection(s2)

{5, 6}

#        @@@@@@@ If Statement @@@@@@@@@@@@
    
    If -> It's Raining : Sit inside
       -> Marks>70% : get Ice-cream
            
            Else Statement ->>>>>> Go Out and Play Football
                              ->>>> Give Practice test 
                
                
                
                ******** IF - Else Statement (Pseudo Code)
                
                ->>>. If (Condition){Starement to be executed}
                ->>>. Else {Statement to be executed }
                    if b > a
                    print ("B is greater than A")( : is defined as Indentation Space )
                    

In [224]:
a=10
b=20
c=30

In [347]:
if (a>b) & (a>c): print ("A is the greatest")
elif (b>a)&(b>c): print (" B is the greatest")
else: print("C is the greatest")

C is the greatest


# if with tuple

In [360]:
tup1=('a','b','c')

In [362]:
if'a'in tup1:
    print ("value 'a' is present in tup1")

value 'a' is present in tup1


In [364]:
if 'z'in tup1:
    print ("value 'z' is present in tup1")
else:
        print("value 'z' is not present in tup1")

value 'z' is not present in tup1


# if with list 

In [366]:
l1=['a','b','c','d']
if l1[1]=='b':l1[1]='z'
l1

['a', 'z', 'c', 'd']

# if with Dictionary

In [384]:
d1=({'k1':10,'k2':20})

#  ############ Looping Statement ############
    ***** Looping Statements are used to repeat a task mulpiple times .
    
    for example -> Keep Filling A Bucket With a Mug Of Water while it is not full.
    
    Example --->> Get Your Salery Creadited at the end of each Month .
    
    1 :> WHILE LOOP --->>>  Enter While Loop
                    ---->>  Test Expression
                    ----->> if True go to Body of While
                
      :>>>>>>> Syntax :->>> While Condition : Execute Statements 
                
    2 :>> For Looping --->>> For Loop is used to iterate over a sequence (tuple, list, dictionary,----)
         
            *** This is the Syntax of for loop 
            
            for val in sequence : Body of For
                

In [391]:
i=1
while i<=10:
    print(i)
    i=i+1

1
2
3
4
5
6
7
8
9
10


In [392]:
i=1
n=2
while i<=10:
    print(n," * ",i," * ",n*i)
    i=i+1

2  *  1  *  2
2  *  2  *  4
2  *  3  *  6
2  *  4  *  8
2  *  5  *  10
2  *  6  *  12
2  *  7  *  14
2  *  8  *  16
2  *  9  *  18
2  *  10  *  20


In [393]:
i=1
n=3
while i<=10:
    print(n," * ",i," * ",n*i)
    i=i+1

3  *  1  *  3
3  *  2  *  6
3  *  3  *  9
3  *  4  *  12
3  *  5  *  15
3  *  6  *  18
3  *  7  *  21
3  *  8  *  24
3  *  9  *  27
3  *  10  *  30


In [394]:
i=1
n=4
while i<=10:
    print(n," * ",i," * ",n*i)
    i=i+1

4  *  1  *  4
4  *  2  *  8
4  *  3  *  12
4  *  4  *  16
4  *  5  *  20
4  *  6  *  24
4  *  7  *  28
4  *  8  *  32
4  *  9  *  36
4  *  10  *  40


In [395]:
i=1
n=5
while i<=10:
    print(n," * ",i," * ",n*i)
    i=i+1

5  *  1  *  5
5  *  2  *  10
5  *  3  *  15
5  *  4  *  20
5  *  5  *  25
5  *  6  *  30
5  *  7  *  35
5  *  8  *  40
5  *  9  *  45
5  *  10  *  50


In [396]:
i=1
n=12
while i<=10:
    print(n," * ",i," * ",n*i)
    i=i+1

12  *  1  *  12
12  *  2  *  24
12  *  3  *  36
12  *  4  *  48
12  *  5  *  60
12  *  6  *  72
12  *  7  *  84
12  *  8  *  96
12  *  9  *  108
12  *  10  *  120


In [397]:
i=1
n=16
while i<=10:
    print(n," * ",i," * ",n*i)
    i=i+1

16  *  1  *  16
16  *  2  *  32
16  *  3  *  48
16  *  4  *  64
16  *  5  *  80
16  *  6  *  96
16  *  7  *  112
16  *  8  *  128
16  *  9  *  144
16  *  10  *  160


# while with list 

In [418]:
l1=[1,2,3,4,5]
i=10

In [421]:
while i<=len(l1):
    l1[i]=l1[i]+100
    i=i+1

In [425]:
l1=['Orange', 'Black', 'Red']
l2=['Chair', 'Book', 'Laptop']
for i in l1:
    for j in l2:
        print(i,j)

Orange Chair
Orange Book
Orange Laptop
Black Chair
Black Book
Black Laptop
Red Chair
Red Book
Red Laptop


# Lambda With Filter

In [430]:
l1=[87,85,5,45,25,5,1,584,25,10]

In [435]:
final_list=list(filter(lambda X:(X%2!=0),l1))
final_list

[1, 3, 5, 7, 9]

# Lambda With Map 

In [433]:
l1=[1,2,3,4,5,6,7,8,9]

In [436]:
list_final_new= list(map(lambda X: X*2,l1)) 
list_final_new

[2, 4, 6, 8, 10, 12, 14, 16, 18]

#                @@@ Functions in Real Life @@@@@@
    
    1 :> Eating 
       
    2 :> Running 
        
    3 :> Cycling     

#                     %%%%%% Python Functions :--->>> Function is a block of code which perform a specific task .
        
                1 :>  Deposit ->>>> Function to Deposit Money 
                
                2 :> Withdraw ->>>> Fuction to Withdraw Money 
                    
                3 :> Balance ->>>> Function to Check Balance 
                    
            ** ->>>> For New Function Creation in Python = def.
            
            ** ->>>  Any value in Round Braces () is called Parameters. 
            
                 def add _10(X): Return X+10 
                    
           *** Lambda Function is also called Anomenous function.
        
         **** Map Function = # Lambda with map 
        
                l1= [1,2,3,4,5,6,7,8,9]

In [234]:
 l1= [1,2,3,4,5,6,7,8,9]

In [235]:
list_final_new = list (map(lambda X: X*2, l1))

In [236]:
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

# *  Reduce Function = From Functools import reduce 

In [ ]:
sum = reduce (lambda X,Y : X+Y, l1 )

In [ ]:
sum = Total Number of l1 (list 1)

#  Libraries in Python :> Python Library is a collection of functions and methods that allows you to perform many actions without writing your code .
    
    1 :> Numpy --->> Numerical Data
        
    2 :> Pandas --->> Data Manipulation     
        
    3 :> Matplotlib ---->> Data Visualization 

#       $$$$$$$ Python Numpy $$$$$$$$$$$
    
    Python Numpy  stands for numericals python and is the core library for numeric and scientific computing .
    
   *  It consists of Multi - Dimentional array object and a collection of routiness for processing those arrays.

1 :> Creating numpy Array ---->>> For One - Dimensional Array (1-D)

In [256]:
import numpy as np

In [259]:
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

# 2 :> Creating numpy Array for (3-D)

In [261]:
import numpy as np

In [263]:
n2=np.array([[10,20,30,40],[40,30,20,10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [264]:
n3=np.array([[[10,20,30,40],[40,50,60,70],[70,80,90,100]]])
n3

array([[[ 10,  20,  30,  40],
        [ 40,  50,  60,  70],
        [ 70,  80,  90, 100]]])

# 3 :> Initializing Numpy Array with Zeros 

In [265]:
import numpy as np 

In [266]:
n1=np.zeros((1,2))

In [267]:
n1

array([[0., 0.]])

In [268]:
n2=np.zeros((5,5))
n2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [269]:
n3=np.full((2,2),10)
n3

array([[10, 10],
       [10, 10]])

In [272]:
n4=np.full((5,5),20)
n4

array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

# 4 :> Initializing Numpy array within a range 

In [273]:
import numpy as np

In [274]:
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [275]:
n2=np.arange(10,50,5)
n2

array([10, 15, 20, 25, 30, 35, 40, 45])

In [277]:
type (n2)

numpy.ndarray

# 5 :> Initializing numpy array with Random Number

In [278]:
import numpy as np

In [285]:
n1=np.random.randint(1,100,5)
n1

array([79, 88, 56, 84, 21])

In [282]:
n1

array([67, 43, 53, 23, 11])

In [284]:
n1

array([73, 40,  4, 76, 67])

In [287]:
n2=np.array([[1,2,3],[4,5,6]])
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [288]:
n2.shape

(2, 3)

# 6 :> Changing Shape In Numpy 

In [289]:
n2=np.array([[1,2,3],[4,5,6]])
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [291]:
n2.shape=(3,2)
n2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [296]:
n2.shape=(2,3)
n2

array([[1, 2, 3],
       [4, 5, 6]])

#                       $$$$$ Joinig Numpy Arrays $$$$$$$$
    
    1 :> Vertical Stack ()

In [297]:
import numpy as np

In [298]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [304]:
import numpy as np

In [306]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.vstack((n2,n1))

array([[40, 50, 60],
       [10, 20, 30]])

# 2 :> Horizontal Stack()

In [307]:
import numpy as np

In [309]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [310]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.hstack((n2,n1))

array([40, 50, 60, 10, 20, 30])

# 3:> Column _ Stack()

In [311]:
import numpy as np 

In [312]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [313]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.column_stack((n2,n1))

array([[40, 10],
       [50, 20],
       [60, 30]])

#           $$$ Numpy Itersection & Differences $$$$ ----->>>>

# 1 :> Numpy Intersection --->>>>

In [314]:
import numpy as np

In [315]:
n1=np.array([10,20,30,40,50,60,70,])
n2=np.array([50,60,70,80,90,100,110])
np.intersect1d(n1,n2)

array([50, 60, 70])

# 2 :> Numpy Differnces --->>>>>

In [316]:
import numpy as np

In [317]:
n1=np.array([10,20,30,40,50,60,70,])
n2=np.array([50,60,70,80,90,100,110])
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [318]:
n1=np.array([10,20,30,40,50,60,70,])
n2=np.array([50,60,70,80,90,100,110])
np.setdiff1d(n2,n1)

array([ 80,  90, 100, 110])

# 3 :> Addition Of Numpy Array -->>

In [319]:
import numpy as np

In [321]:
n1=np.array([10,20,30,40,50,60,70,])
n2=np.array([50,60,70,80,90,100,110])
np.sum([n1,n2])

840

In [322]:
n1=np.array([10,20,30,40,50,60,70,])
n2=np.array([50,60,70,80,90,100,110])
np.sum([n1,n2],axis=0)

array([ 60,  80, 100, 120, 140, 160, 180])

In [323]:
n1=np.array([10,20,30,40,50,60,70,])
n2=np.array([50,60,70,80,90,100,110])
np.sum([n1,n2],axis=1)

array([280, 560])

#                    ##### Numpy Array Mathematics ########

# 1 :> Basic Addition

In [324]:
n1=np.array([10,20,30])
n1=n1+1
n1

array([11, 21, 31])

In [325]:
n1=np.array([10,20,30])
n1=n1+5
n1

array([15, 25, 35])

In [326]:
n1=np.array([10,20,30])
n1=n1+6
n1

array([16, 26, 36])

# 2 :> Basic Substraction

In [327]:
n1=np.array([10,20,30])
n1=n1-1
n1

array([ 9, 19, 29])

In [328]:
n1=np.array([10,20,30])
n1=n1-15
n1

array([-5,  5, 15])

In [329]:
n1=np.array([10,20,30])
n1=n1-3
n1

array([ 7, 17, 27])

# 3 :> Basic Multiplication 

In [330]:
n1=np.array([10,20,30])
n1=n1*2
n1

array([20, 40, 60])

In [331]:
n1=np.array([10,20,30])
n1=n1*6
n1

array([ 60, 120, 180])

# 4 :> Basic Division 

In [332]:
n1=np.array([10,20,30])
n1=n1/2
n1

array([ 5., 10., 15.])

In [333]:
n1=np.array([10,20,30])
n1=n1/3
n1

array([ 3.33333333,  6.66666667, 10.        ])

# 5 :> Mean 

In [334]:
n1=np.array([10,20,30])
np.mean(n1)

20.0

In [335]:
n2=np.array([50,60,70,80])
np.mean(n2)

65.0

# 6 :> Median

In [337]:
n1=np.array([10,20,30])
np.median(n1)

20.0

In [339]:
n2=np.array([50,60,70,80,90,100])
np.median(n2)

75.0

# 7 :> Standard Deviation 

In [340]:
n2=np.array([50,60,70,80])
np.std(n2)

11.180339887498949

In [341]:
n2=np.array([50,60,70,80,90,100])
np.std(n2)

17.07825127659933

# 8 :> Saving Numpy Array 

In [342]:
import numpy as np 

In [344]:
n2=np.array([50,60,70,80,90,100])
np.save('my_numpy',n2)

# 9 :> Loading Numpy Array

In [346]:
n2=np.load('my_numpy.npy')
n2

array([ 50,  60,  70,  80,  90, 100])